import styled from 'styled-components';

export const Container = styled.section`
  width: 90%;
  background-color: rgb(228, 228, 228);
  border-radius: 5px;
  padding: 25px;
  h1 {
    font-size: 20px;
  }

  .pj {
    background-color: whitesmoke;
    padding: 15px;
    margin: 15px;
    border-radius: 5px;
    h1 {
      color: black;
      font-size: 20px;
    }
    p {
      color: #777777;
      font-size: 15px;
    }
    .btn-git-net {
      outline: none;
      border: none;
      background-color: transparent;
      font-size: 25px;
      margin: 2px;
    }

    .btn-git-net:hover {
      outline: none;
      border: none;
      color: rgb(133, 133, 133);
      font-size: 25px;
      margin: 2px;
    }

    a {
      color: inherit; /* blue colors for links too */
      text-decoration: inherit; /* no underline */
    }
  }

  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-7 23:1:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
  @-webkit-keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
  @keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
`;
