import styled from 'styled-components';

export const Container = styled.section`
  background-color: rgb(228, 228, 228);
  border-radius: 5px;
  padding: 25px;
  width: 90%;

  .contato {
    display: flex;
    flex-direction: column;
    border-radius: 5px;
    background-color: #f1f0f0;
    padding: 15px;
    border-top: solid 5px #777777;

    .forms {
      background-color: transparent;

      h1 {
        font-family: 'Josefin Sans', sans-serif;
        color: #000000;
        font-size: 35px;
        margin-bottom: 15px;
      }

      h3 {
        font-family: 'Josefin Sans', sans-serif;
        color: #777777;
        font-size: 20px;
        margin-bottom: 25px;
      }

      form {
        display: grid;
        grid-template-columns: 1fr;
        grid-template-rows: 1fr 1fr 2fr;

        input {
          color: #000000;
          width: 450px;
          height: 35px;
          outline: none;
          background-color: whitesmoke;
          border: 1.5px solid #5e5d5d;
          border-radius: 5px;
          text-align: center;
          font-size: 15px;
          font-family: 'Josefin Sans', sans-serif;
        }

        textarea {
          color: #000000;
          width: 450px;
          height: 100px;
          min-width: 450px;
          min-height: 100px;
          max-width: 450px;
          max-height: 100px;
          outline: none;
          background-color: whitesmoke;
          border: 1.5px solid #5e5d5d;
          border-radius: 5px;
          text-align: center;
          font-size: 15px;
          font-family: 'Josefin Sans', sans-serif;
        }
      }
      button {
        background-color: #000000;
        color: white;
        width: 150px;
        height: 50px;
        outline: none;
        border: none;
        border-radius: 5px;
        margin-top: 20px;
        text-align: center;
        font-size: 17px;
        &:hover {
          background-color: transparent;
          color: #000000;
          border: 2px solid #000000;
          font-size: 17px;
        }
      }
    }
  }

  h1 {
    font-size: 20px;
  }

  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-7 23:1:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
  @-webkit-keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
  @keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
`;
