import styled from 'styled-components';

export const Container = styled.section`
  display: flex;
  flex-direction: column;
  border-radius: 5px;

  width: 100%;
  box-sizing: border-box;
  margin-top: 5%;

  .xp {
    img {
      width: 25px;
      height: 25px;
      transform: translateY(5px);
    }
  }

  form {
    display: flex;
  }
  .text-area_admin {
    width: 80%;
    font-size: 20px;
    margin-top: 2%;
    margin-bottom: 2%;
    -webkit-animation: slide-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation-delay: 1.4s;
    img {
      width: 30px;
      height: 30px;
      transform: translateY(5px);
    }

    textarea {
      outline: none;
      border: 3px solid #626567;
      border-radius: 15px;
      padding: 8% 5%;
    }
  }

  .text-area_admin {
    display: flex;
    button {
      border: none;
      margin: 0;
      padding: 0;
      width: auto;
      overflow: visible;
      background: transparent;
      position: absolute;
      margin-left: 90%;
      margin-top: 2%;
      cursor: pointer;
      img {
        transform: scale(1.3);
      }
    }
  }

  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-7 23:1:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
  @-webkit-keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
  @keyframes scale-in-center {
    0% {
      -webkit-transform: scale(0);
      transform: scale(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      opacity: 1;
    }
  }
`;
