import styled from 'styled-components';

export const Container = styled.header`
  width: 100%;
  grid-template-columns: 1fr;

  .navbar {
    width: 100%;
    background-color: transparent;
  }

  .navbar .lista {
    display: flex;
    width: 40%;
    justify-content: start;
    margin-top: 3%;
  }

  .navbar .lista li {
    font-size: 18px;
    text-align: left;
    margin-right: 5%;

    a {
      font-family: 'Gothic A1', sans-serif;
      text-decoration: none;
      color: black;
      padding: 5%;

      &:hover {
        border-top: solid 2px black;
        border-bottom: solid 2px black;
      }
    }
  }

  -webkit-animation: tracking-in-expand-fwd-top 0.8s cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: tracking-in-expand-fwd-top 0.8s cubic-bezier(0.215, 0.61, 0.355, 1) both;

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-7 23:3:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation tracking-in-expand-fwd-top
 * ----------------------------------------
 */
  @-webkit-keyframes tracking-in-expand-fwd-top {
    0% {
      letter-spacing: -0.5em;
      -webkit-transform: translateZ(-700px) translateY(-500px);
      transform: translateZ(-700px) translateY(-500px);
      opacity: 0;
    }
    40% {
      opacity: 0.6;
    }
    100% {
      -webkit-transform: translateZ(0) translateY(0);
      transform: translateZ(0) translateY(0);
      opacity: 1;
    }
  }
  @keyframes tracking-in-expand-fwd-top {
    0% {
      letter-spacing: -0.5em;
      -webkit-transform: translateZ(-700px) translateY(-500px);
      transform: translateZ(-700px) translateY(-500px);
      opacity: 0;
    }
    40% {
      opacity: 0.6;
    }
    100% {
      -webkit-transform: translateZ(0) translateY(0);
      transform: translateZ(0) translateY(0);
      opacity: 1;
    }
  }
`;
